version: '3'

services:
  db:
    image: 'postgres'
    volumes:
      - '.data/db:/var/lib/postgresql/data'
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=fake
      - POSTGRES_PASSWORD=fakepassword
