###

GET http://localhost:8080

###

GET http://localhost:8080/v1/word/random

###

POST http://localhost:8080/v1/word
Content-Type: application/json

{
  "word": "door",
  "language_code": "fr"
}

###

POST http://localhost:8080/v1/word/5/tr/translate
Content-Type: application/json

{
  "content": "(n) Adam"
}

###

GET http://localhost:8080/v1/word/random/10/11/translate
